# Generated by Django 5.2.5 on 2025-08-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='first name', max_length=30)),
                ('last_name', models.CharField(help_text='last name', max_length=50)),
                ('age', models.IntegerField(default=18, help_text='age')),
                ('country', models.CharField(help_text='country', max_length=30)),
            ],
        ),
    ]
