# Generated by Django 5.2.5 on 2025-08-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_person_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='persona',
        ),
    ]
