# Generated by Django 5.2.5 on 2025-08-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_person_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, help_text='email', max_length=254, null=True),
        ),
    ]
